/*
 * X32Output.h
 *
 *  Created on: 4 févr. 2015
 *      Author: patrick
 */

#ifndef X32OUTPUT_H_
#define X32OUTPUT_H_

X32command Xoutput[] = {
		{"/outputs/main/01",				{OMAIN}, F_FND, {0}},
		{"/outputs/main/01/src",		{I32}, F_XET, {0}},
		{"/outputs/main/01/pos",		{I32}, F_XET, {0}},
		{"/outputs/main/01/delay",			{OMAIND}, F_FND, {0}},
		{"/outputs/main/01/delay/on",	{I32}, F_XET, {0}},
		{"/outputs/main/01/delay/time",	{F32}, F_XET, {0}},
		{"/outputs/main/02",				{OMAIN}, F_FND, {0}},
		{"/outputs/main/02/src",		{I32}, F_XET, {0}},
		{"/outputs/main/02/pos",		{I32}, F_XET, {0}},
		{"/outputs/main/02/delay",			{OMAIND}, F_FND, {0}},
		{"/outputs/main/02/delay/on",	{I32}, F_XET, {0}},
		{"/outputs/main/02/delay/time",	{F32}, F_XET, {0}},
		{"/outputs/main/03",				{OMAIN}, F_FND, {0}},
		{"/outputs/main/03/src",		{I32}, F_XET, {0}},
		{"/outputs/main/03/pos",		{I32}, F_XET, {0}},
		{"/outputs/main/03/delay",			{OMAIND}, F_FND, {0}},
		{"/outputs/main/03/delay/on",	{I32}, F_XET, {0}},
		{"/outputs/main/03/delay/time",	{F32}, F_XET, {0}},
		{"/outputs/main/04",				{OMAIN}, F_FND, {0}},
		{"/outputs/main/04/src",		{I32}, F_XET, {0}},
		{"/outputs/main/04/pos",		{I32}, F_XET, {0}},
		{"/outputs/main/04/delay",			{OMAIND}, F_FND, {0}},
		{"/outputs/main/04/delay/on",	{I32}, F_XET, {0}},
		{"/outputs/main/04/delay/time",	{F32}, F_XET, {0}},
		{"/outputs/main/05",				{OMAIN}, F_FND, {0}},
		{"/outputs/main/05/src",		{I32}, F_XET, {0}},
		{"/outputs/main/05/pos",		{I32}, F_XET, {0}},
		{"/outputs/main/05/delay",			{OMAIND}, F_FND, {0}},
		{"/outputs/main/05/delay/on",	{I32}, F_XET, {0}},
		{"/outputs/main/05/delay/time",	{F32}, F_XET, {0}},
		{"/outputs/main/06",				{OMAIN}, F_FND, {0}},
		{"/outputs/main/06/src",		{I32}, F_XET, {0}},
		{"/outputs/main/06/pos",		{I32}, F_XET, {0}},
		{"/outputs/main/06/delay",			{OMAIND}, F_FND, {0}},
		{"/outputs/main/06/delay/on",	{I32}, F_XET, {0}},
		{"/outputs/main/06/delay/time",	{F32}, F_XET, {0}},
		{"/outputs/main/07",				{OMAIN}, F_FND, {0}},
		{"/outputs/main/07/src",		{I32}, F_XET, {0}},
		{"/outputs/main/07/pos",		{I32}, F_XET, {0}},
		{"/outputs/main/07/delay",			{OMAIND}, F_FND, {0}},
		{"/outputs/main/07/delay/on",	{I32}, F_XET, {0}},
		{"/outputs/main/07/delay/time",	{F32}, F_XET, {0}},
		{"/outputs/main/08",				{OMAIN}, F_FND, {0}},
		{"/outputs/main/08/src",		{I32}, F_XET, {0}},
		{"/outputs/main/08/pos",		{I32}, F_XET, {0}},
		{"/outputs/main/08/delay",			{OMAIND}, F_FND, {0}},
		{"/outputs/main/08/delay/on",	{I32}, F_XET, {0}},
		{"/outputs/main/08/delay/time",	{F32}, F_XET, {0}},
		{"/outputs/main/09",				{OMAIN}, F_FND, {0}},
		{"/outputs/main/09/src",		{I32}, F_XET, {0}},
		{"/outputs/main/09/pos",		{I32}, F_XET, {0}},
		{"/outputs/main/09/delay",			{OMAIND}, F_FND, {0}},
		{"/outputs/main/09/delay/on",	{I32}, F_XET, {0}},
		{"/outputs/main/09/delay/time",	{F32}, F_XET, {0}},
		{"/outputs/main/10",				{OMAIN}, F_FND, {0}},
		{"/outputs/main/10/src",		{I32}, F_XET, {0}},
		{"/outputs/main/10/pos",		{I32}, F_XET, {0}},
		{"/outputs/main/10/delay",			{OMAIND}, F_FND, {0}},
		{"/outputs/main/10/delay/on",	{I32}, F_XET, {0}},
		{"/outputs/main/10/delay/time",	{F32}, F_XET, {0}},
		{"/outputs/main/11",				{OMAIN}, F_FND, {0}},
		{"/outputs/main/11/src",		{I32}, F_XET, {0}},
		{"/outputs/main/11/pos",		{I32}, F_XET, {0}},
		{"/outputs/main/11/delay",			{OMAIND}, F_FND, {0}},
		{"/outputs/main/11/delay/on",	{I32}, F_XET, {0}},
		{"/outputs/main/11/delay/time",	{F32}, F_XET, {0}},
		{"/outputs/main/11",				{OMAIN}, F_FND, {0}},
		{"/outputs/main/12/src",		{I32}, F_XET, {0}},
		{"/outputs/main/12/pos",		{I32}, F_XET, {0}},
		{"/outputs/main/12/delay",			{OMAIND}, F_FND, {0}},
		{"/outputs/main/12/delay/on",	{I32}, F_XET, {0}},
		{"/outputs/main/12/delay/time",	{F32}, F_XET, {0}},
		{"/outputs/main/13",				{OMAIN}, F_FND, {0}},
		{"/outputs/main/13/src",		{I32}, F_XET, {0}},
		{"/outputs/main/13/pos",		{I32}, F_XET, {0}},
		{"/outputs/main/13/delay",			{OMAIND}, F_FND, {0}},
		{"/outputs/main/13/delay/on",	{I32}, F_XET, {0}},
		{"/outputs/main/13/delay/time",	{F32}, F_XET, {0}},
		{"/outputs/main/14",				{OMAIN}, F_FND, {0}},
		{"/outputs/main/14/src",		{I32}, F_XET, {0}},
		{"/outputs/main/14/pos",		{I32}, F_XET, {0}},
		{"/outputs/main/14/delay",			{OMAIND}, F_FND, {0}},
		{"/outputs/main/14/delay/on",	{I32}, F_XET, {0}},
		{"/outputs/main/14/delay/time",	{F32}, F_XET, {0}},
		{"/outputs/main/15",				{OMAIN}, F_FND, {0}},
		{"/outputs/main/15/src",		{I32}, F_XET, {0}},
		{"/outputs/main/15/pos",		{I32}, F_XET, {0}},
		{"/outputs/main/15/delay",			{OMAIND}, F_FND, {0}},
		{"/outputs/main/15/delay/on",	{I32}, F_XET, {0}},
		{"/outputs/main/15/delay/time",	{F32}, F_XET, {0}},
		{"/outputs/main/16",				{OMAIN}, F_FND, {0}},
		{"/outputs/main/16/src",		{I32}, F_XET, {0}},
		{"/outputs/main/16/pos",		{I32}, F_XET, {0}},
		{"/outputs/main/16/delay",			{OMAIND}, F_FND, {0}},
		{"/outputs/main/16/delay/on",	{I32}, F_XET, {0}},
		{"/outputs/main/16/delay/time",	{F32}, F_XET, {0}},

		{"/outputs/aux/01",					{OMAIN}, F_FND, {0}},
		{"/outputs/aux/01/src",			{I32}, F_XET, {0}},
		{"/outputs/aux/01/pos",			{I32}, F_XET, {0}},
		{"/outputs/aux/02",					{OMAIN}, F_FND, {0}},
		{"/outputs/aux/02/src",			{I32}, F_XET, {0}},
		{"/outputs/aux/02/pos",			{I32}, F_XET, {0}},
		{"/outputs/aux/03",					{OMAIN}, F_FND, {0}},
		{"/outputs/aux/03/src",			{I32}, F_XET, {0}},
		{"/outputs/aux/03/pos",			{I32}, F_XET, {0}},
		{"/outputs/aux/04",					{OMAIN}, F_FND, {0}},
		{"/outputs/aux/04/src",			{I32}, F_XET, {0}},
		{"/outputs/aux/04/pos",			{I32}, F_XET, {0}},
		{"/outputs/aux/05",					{OMAIN}, F_FND, {0}},
		{"/outputs/aux/05/src",			{I32}, F_XET, {0}},
		{"/outputs/aux/05/pos",			{I32}, F_XET, {0}},
		{"/outputs/aux/06",					{OMAIN}, F_FND, {0}},
		{"/outputs/aux/06/src",			{I32}, F_XET, {0}},
		{"/outputs/aux/06/pos",			{I32}, F_XET, {0}},


		{"/outputs/p16/01",					{OMAIN}, F_FND, {0}},
		{"/outputs/p16/01/src",			{I32}, F_XET, {0}},
		{"/outputs/p16/01/pos",			{I32}, F_XET, {0}},
		{"/outputs/p16/02",					{OMAIN}, F_FND, {0}},
		{"/outputs/p16/02/src",			{I32}, F_XET, {0}},
		{"/outputs/p16/02/pos",			{I32}, F_XET, {0}},
		{"/outputs/p16/03",					{OMAIN}, F_FND, {0}},
		{"/outputs/p16/03/src",			{I32}, F_XET, {0}},
		{"/outputs/p16/03/pos",			{I32}, F_XET, {0}},
		{"/outputs/p16/04",					{OMAIN}, F_FND, {0}},
		{"/outputs/p16/04/src",			{I32}, F_XET, {0}},
		{"/outputs/p16/04/pos",			{I32}, F_XET, {0}},
		{"/outputs/p16/05",					{OMAIN}, F_FND, {0}},
		{"/outputs/p16/05/src",			{I32}, F_XET, {0}},
		{"/outputs/p16/05/pos",			{I32}, F_XET, {0}},
		{"/outputs/p16/06",					{OMAIN}, F_FND, {0}},
		{"/outputs/p16/06/src",			{I32}, F_XET, {0}},
		{"/outputs/p16/06/pos",			{I32}, F_XET, {0}},
		{"/outputs/p16/07",					{OMAIN}, F_FND, {0}},
		{"/outputs/p16/07/src",			{I32}, F_XET, {0}},
		{"/outputs/p16/07/pos",			{I32}, F_XET, {0}},
		{"/outputs/p16/08",					{OMAIN}, F_FND, {0}},
		{"/outputs/p16/08/src",			{I32}, F_XET, {0}},
		{"/outputs/p16/08/pos",			{I32}, F_XET, {0}},
		{"/outputs/p16/09",					{OMAIN}, F_FND, {0}},
		{"/outputs/p16/09/src",			{I32}, F_XET, {0}},
		{"/outputs/p16/09/pos",			{I32}, F_XET, {0}},
		{"/outputs/p16/10",					{OMAIN}, F_FND, {0}},
		{"/outputs/p16/10/src",			{I32}, F_XET, {0}},
		{"/outputs/p16/10/pos",			{I32}, F_XET, {0}},
		{"/outputs/p16/11",					{OMAIN}, F_FND, {0}},
		{"/outputs/p16/11/src",			{I32}, F_XET, {0}},
		{"/outputs/p16/11/pos",			{I32}, F_XET, {0}},
		{"/outputs/p16/12",					{OMAIN}, F_FND, {0}},
		{"/outputs/p16/12/src",			{I32}, F_XET, {0}},
		{"/outputs/p16/12/pos",			{I32}, F_XET, {0}},
		{"/outputs/p16/13",					{OMAIN}, F_FND, {0}},
		{"/outputs/p16/13/src",			{I32}, F_XET, {0}},
		{"/outputs/p16/13/pos",			{I32}, F_XET, {0}},
		{"/outputs/p16/14",					{OMAIN}, F_FND, {0}},
		{"/outputs/p16/14/src",			{I32}, F_XET, {0}},
		{"/outputs/p16/14/pos",			{I32}, F_XET, {0}},
		{"/outputs/p16/15",					{OMAIN}, F_FND, {0}},
		{"/outputs/p16/15/src",			{I32}, F_XET, {0}},
		{"/outputs/p16/15/pos",			{I32}, F_XET, {0}},
		{"/outputs/p16/16",					{OMAIN}, F_FND, {0}},
		{"/outputs/p16/16/src",			{I32}, F_XET, {0}},
		{"/outputs/p16/16/pos",			{I32}, F_XET, {0}},

		{"/outputs/aes/01",					{OMAIN}, F_FND, {0}},
		{"/outputs/aes/01/src",			{I32}, F_XET, {0}},
		{"/outputs/aes/01/pos",			{I32}, F_XET, {0}},
		{"/outputs/aes/02",					{OMAIN}, F_FND, {0}},
		{"/outputs/aes/02/src",			{I32}, F_XET, {0}},
		{"/outputs/aes/02/pos",			{I32}, F_XET, {0}},

		{"/outputs/rec/01",					{OMAIN}, F_FND, {0}},
		{"/outputs/rec/01/src",			{I32}, F_XET, {0}},
		{"/outputs/rec/01/pos",			{I32}, F_XET, {0}},
		{"/outputs/rec/02",					{OMAIN}, F_FND, {0}},
		{"/outputs/rec/02/src",			{I32}, F_XET, {0}},
		{"/outputs/rec/02/pos",			{I32}, F_XET, {0}},
};
int Xoutput_max = sizeof(Xoutput) / sizeof(X32command);


#endif /* X32OUTPUT_H_ */
